spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: Siiu Seguimientos proyectos
  datasource:
    url:  ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        order_inserts: true
        dialect: org.hibernate.dialect.OracleDialect

siiu-seguimproyectos-api:
  openapi:
    dev-url: ${DEV_API_URL}

server:
  port: ${DEV_PORT}

logging:
  level:
    root: DEBUG
    org.springframework: DEBUG

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: "SiiuSeguimproyectosBackApplication"

springdoc:
  packages-to-scan: "package1, package2, com.sitas.checkin"
  paths-to-match: "/v1, /api/balance/**, *, **, /*, /**"