spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: Siiu Seguimientos proyectos
  datasource:
    url:  jdbc:oracle:thin:@//ndbsdev.udea.local:1521/UDEA_DEV.udea.cloud
    username: bupp
    password: Jf1_UO_lRbw5
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        order_inserts: true
        dialect: org.hibernate.dialect.OracleDialect

siiu-seguimproyectos-api:
  openapi:
    dev-url: http://localhost:8080

server:
  port: 8080

logging:
  level:
    root: DEBUG
    org.springframework: DEBUG

springdoc:
  packages-to-scan: "package1, package2, com.udea.siiuseguimproyectosback"
  paths-to-match: "/v1, /api/balance/**, *, **, /*, /**"