services:
  backend:
    image: backend_service
    build:
      context: ..
      dockerfile: docker/Dockerfile
    env_file:
      - ../.env
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs
    depends_on:
        - oracle

  oracle:
    image: gvenzl/oracle-free:latest
    ports:
      - "1521:1521"
    environment:
      - ORACLE_ALLOW_REMOTE=true
      - ORACLE_PASSWORD=password
    volumes:
      - ./data:/opt/oracle/oradata
