services:
  backend:
    image: backend_service
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@//ndbsdev.udea.local:1521/UDEA_DEV.udea.cloud
      SPRING_DATASOURCE_USERNAME: bupp
      SPRING_DATASOURCE_PASSWORD: Jf1_UO_lRbw5
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs
